config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: { registrations: "admin/registrations",sessions: "admin/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "admin#account"
  get '/sign_in', to: 'static_pages#index'

  resources :admin, except: [:create] do
    member do
      get :account
    end
  end

  resources :categories

  resources :questions

  resources :polls do
    collection do
      get :update_questions
      get :get_widget
    end
  end

  post 'create_admin' => 'admin#create', as: :create_admin

end

app/views/admin/_delete_admin_modal.html.haml
.modal.fade.in.new-admin-writer{:id => "deleteAdmin_#{index}","aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-body
        %h1 Are you sure you want to delete this writer?
        .field.form-group
          %label.col-sm-4.control-label
            Email
          %br
          .col-sm-8
            %p #{admin.email}
        .field.form-group
          %label.col-sm-4.control-label
            Name
          %br
          .col-sm-8
            %p #{admin.name}
        .field.form-group
          %label.col-sm-4.control-label
            Last Name
          %br
          .col-sm-8
            %p #{admin.last_name}
        .field.form-group
          %label.col-sm-4.control-label
            Password
          %br
          .col-sm-8
            %p ********
        .field.form-group
          %label.col-sm-4.control-label
            Password Confirmation
          %br
          .col-sm-8
            %p ********
      .modal-btn-area
        = link_to "Delete",admin_path(admin),method: "delete",class: "btn btn-danger"

app/views/admin/_edit.html.haml
.modal-dialog{:role => "document"}
  .modal-content
    .modal-body
      %h1 Edit Writer
      = render 'form'

app/views/admin/_form.html.haml
= form_for @admin, class: "form-horizontal" do |f|
  .field.form-group
    = f.label :email, class: "col-sm-4 control-label"
    %br
    .col-sm-8
      = f.email_field :email, autofocus: true, class: "form-control",disabled: true
  .field.form-group
    = f.label :name, class: "col-sm-4 control-label"
    %br
    .col-sm-8
      = f.text_field :name, class: "form-control"
  .field.form-group
    = f.label :last_name, class: "col-sm-4 control-label"
    %br
    .col-sm-8
      = f.text_field :last_name, class: "form-control"
  .field.form-group.password-group
    = f.label :password, class: "col-sm-4 control-label"
    - if @minimum_password_length
      %em
        (#{@minimum_password_length} characters minimum)
    %br
    .col-sm-8
      = f.password_field :password, autocomplete: "off", class: "form-control password-field",placeholder: "Enter passwords if passwords are to be changed."
  .field.form-group.password-confirmation-group
    = f.label :password_confirmation, class: "col-sm-4 control-label"
    %br
    .col-sm-8
      = f.password_field :password_confirmation, autocomplete: "off", class: "form-control password-confirmation-field"
  .actions.right
    = f.submit "Save", class: "update-user btn btn-success"

app/views/admin/_show.html.haml
.modal-dialog{:role => "document"}
  .modal-content
    .modal-body
      %h1 View Writer
      .field.form-group
        %label.col-sm-4.control-label
          Email
        %br
        .col-sm-8
          %p #{@admin.email}
      .field.form-group
        %label.col-sm-4.control-label
          Name
        %br
        .col-sm-8
          %p #{@admin.name}
      .field.form-group
        %label.col-sm-4.control-label
          Last Name
        %br
        .col-sm-8
          %p #{@admin.last_name}
      .field.form-group
        %label.col-sm-4.control-label
          Password
        %br
        .col-sm-8
          %p ********
      .field.form-group
        %label.col-sm-4.control-label
          Password Confirmation
        %br
        .col-sm-8
          %p ********

app/views/admin/account.html.haml
.row
  %script{:src => "http://c17cfaa4.ngrok.io/assets/widgets.js", :type => "text/javascript"}
  #widget-container.px300{"data-value" => "8"}
  .col-md-7
    %button.btn.edit-profile-btn.pull-right{"data-target" => "#editProfile", "data-toggle" => "modal", :type => "button"}
      %a.fa.fa-pencil
    .panel.panel-default
      .panel-heading
        %h4 User Profile
      .panel-body
        .box.box-info
          .box-body
            .col-sm-6
              %div{:align => "center"}
                %img#profile-image1.img-circle.img-responsive{:alt => "User Pic", :src => "https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg"}/
                %input#profile-image-upload.hidden{:type => "file"}/
                %div{:style => "color:#999;"} click here to change profile image
                / Upload Image Js And Css
              %br/
              / /input-group
            .col-sm-6
              %h4{:style => "color:#00b1b1;"} #{@admin.name}
              %span
                - if @admin.super_admin?
                  %p Admin
                - else
                  %p Writer
            .clearfix
            %hr{:style => "margin:5px 0 5px 0;"}
            .col-sm-5.col-xs-6.tital Name:
            .col-sm-7.col-xs-6 #{@admin.name}
            .clearfix
            .bot-border
            .col-sm-5.col-xs-6.tital Last Name:
            .col-sm-7 #{@admin.last_name}
            .clearfix
            .bot-border
            .col-sm-5.col-xs-6.tital E-Mail:
            .col-sm-7 #{@admin.email}
            .clearfix
            .bot-border
            / /.box-body
          / /.box
#editProfile.modal.fade.in.new-admin-writer{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-body
        %h1 Edit Profile
        = render 'form'
:javascript
  $(function() {
      $('#profile-image1').on('click', function() {
          $('#profile-image-upload').click();
      });
  });

app/views/admin/edit.js.erb
$("#editAdmin").html("<%= escape_javascript(render 'edit') %>")
$("#editAdmin").modal("show")

app/views/admin/index.html.haml
%h1 Writers
%table.table.table-bordered.table-striped
  %thead
    %tr
      %th Name
      %th Last Name
      %th Email
      %th Password
      %th Password
      %th
      %th.delet-td
  %tbody
    - @admins.try(:each_with_index) do |admin,index|
      %tr
        %td #{admin.name}
        %td #{admin.last_name}
        %td #{admin.email}
        %td ************
        %td ************
        %td.text-center.editing-td
          = link_to admin_path(admin),remote: true do
            %i.fa.fa-eye.edit-admin
          = link_to edit_admin_path(admin),remote: true do
            %i.fa.fa-pencil
        %td.text-center.delet-td
          %a.fa.fa-trash{"data-target" => "#deleteAdmin_#{index}", "data-toggle" => "modal", :type => "button"}
          / = render "delete_admin_modal", locales: {admin: admin}
          = render partial: "delete_admin_modal", locals: {admin: admin,index: index}
- if current_admin.super_admin?
  %button.btn.btn-wirte{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"}
    Create Writer
#myModal.modal.fade.in.new-admin-writer{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-body
        %h1 Create a new Writer
        = form_for @admin, url: create_admin_path, class: "form-horizontal" do |f|
          .field.form-group
            = f.label :email, class: "col-sm-4 control-label"
            %br
            .col-sm-8
              = f.email_field :email, autofocus: true, class: "form-control"
          .field.form-group
            = f.label :name, class: "col-sm-4 control-label"
            %br
            .col-sm-8
              = f.text_field :name, class: "form-control"
          .field.form-group
            = f.label :last_name, class: "col-sm-4 control-label"
            %br
            .col-sm-8
              = f.text_field :last_name, class: "form-control"
          .field.form-group
            = f.label :password, class: "col-sm-4 control-label"
            - if @minimum_password_length
              %em
                (#{@minimum_password_length} characters minimum)
            %br
            .col-sm-8
              = f.password_field :password, autocomplete: "off", class: "form-control"
          .field.form-group
            = f.label :password_confirmation, class: "col-sm-4 control-label"
            %br
            .col-sm-8
              = f.password_field :password_confirmation, autocomplete: "off", class: "form-control"
          .actions.modal-btn-area
            = f.submit "Create"
#viewAdmin.modal.fade.in.new-admin-writer.text-center{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
#editAdmin.modal.fade.in.new-admin-writer.text-center{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}

app/views/admin/new.html.haml
%h2
  this is the new user form
= form_for @admin, url: create_admin_path do |f|
  .field
    = f.label :email
    %br
    = f.email_field :email, autofocus: true
  .field
    = f.label :name
    %br
    = f.text_field :name
  .field
    = f.label :last_name
    %br
    = f.text_field :last_name
  .field
    = f.label :password
    - if @minimum_password_length
      %em
        (#{@minimum_password_length} characters minimum)
    %br
    = f.password_field :password, autocomplete: "off"
  .field
    = f.label :password_confirmation
    %br
    = f.password_field :password_confirmation, autocomplete: "off"
  .actions
    = f.submit "Create"

app/views/admin/show.js.erb
$("#viewAdmin").html("<%= escape_javascript(render 'show') %>")
$("#viewAdmin").modal("show")