config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: { registrations: "admin/registrations",sessions: "admin/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "admin#account"
  get '/sign_in', to: 'static_pages#index'

  resources :admin, except: [:create] do
    member do
      get :account
    end
  end

  resources :categories

  resources :questions

  resources :polls do
    collection do
      get :update_questions
      get :get_widget
    end
  end

  post 'create_admin' => 'admin#create', as: :create_admin

end

app/models/poll.rb
class Poll < ApplicationRecord
  belongs_to :category
  belongs_to :admin
  has_many :poll_questions
  has_many :questions, through: :poll_questions
  default_scope { order(created_at: :desc) }

  def self.filter_polls(poll_params)
    if poll_params[:poll_type].blank? && !poll_params[:category_id].blank?
      @polls = Poll.where(category_id: poll_params[:category_id])
    elsif poll_params[:category_id].blank? && !poll_params[:poll_type].blank?
      @polls = Poll.where(poll_type: poll_params[:poll_type])
    elsif !poll_params[:poll_type].blank? && !poll_params[:category_id].blank?
      @polls = Poll.where(poll_type: poll_params[:poll_type], category_id: poll_params[:category_id])
    else
      @polls = Poll.all
    end
    @polls
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_filter :set_layout
  before_action :set_poll, only: [:update, :destroy, :edit, :show, :update,:get_widget]
  protect_from_forgery with: :exception, except: [:get_widget]
  before_action :authenticate_admin!, except: [:get_widget]

  def index
    @categories = Category.all
    if params[:poll].blank?
      @polls = Poll.all.includes(:category , :questions)
    else
      @polls = Poll.filter_polls(poll_params).includes(:category , :questions)
    end
    @polls = @polls.paginate(:page => params[:page], :per_page => 10)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update_questions
    if params[:poll].blank?
      @questions = Question.all.includes(:category , :polls)
    else
      @questions = Question.filter_questions(poll_params).includes(:category , :polls)
    end
    @questions = @questions.paginate(:page => params[:page], :per_page => 10)
    respond_to do |format|
      format.js
    end
  end

  def new
    @poll = Poll.new
    @categories = Category.all
    @questions = Question.all.includes(:category , :polls).paginate(:page => params[:page], :per_page => 10)
  end

  def create
    @question_ids = params[:question_ids].split(",")
    questions = Question.where(id: @question_ids)
    @poll = Poll.new(poll_params)
    if @poll.save
      @poll.questions << questions
      redirect_to polls_url, notice: 'poll was successfully created.'
    else
      redirect_to polls_url, notice: 'poll could not be created.'
    end
  end
  def get_widget
    # @poll = Poll.first
    @poll_questions = @poll.questions
    @category = @poll.category
    # Store HTML in a variable rather than returning in to the browser
    # html = "<strong>lalala!</strong>"
    html = view_context.render 'widget'
    # Build a JSON object containing our HTML
    json = {"html" => html}.to_json
    # Get the name of the JSONP callback created by jQuery
    callback = params[:callback]
    # Wrap the JSON object with a call to the JSONP callback
    jsonp = callback + "(" + json + ")"
    # Send result to the browser
    puts "========================"
    puts "========================"
    puts "lalalalallalalalalallala"
    puts "========================"
    puts "========================"
    render js: jsonp, content_type: "application/javascript"
  end

  def show
    @poll_questions = @poll.questions
    @category = @poll.category
    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    @poll.destroy
    redirect_back(fallback_location: :back,notice: "poll was successfully deleted.")
  end

  private

    def set_poll
      @poll = Poll.find(params[:id])
    end

    def set_layout
      self.class.layout "dashboard"
    end

    def poll_params
      params.require(:poll).permit(:category_id,:admin_id,:poll_type,:name,:question_type)
    end
end

app/views/polls/_polls_table.html.haml
%table.table.table-bordered.table-striped.question-table
  %thead
    %tr
      %th Poll Name/Title
      %th Category
      %th Type
      %th # of qestions
      %th Widget ID
      %th
      %th.delet-td
  %tbody
    - @polls.each_with_index do |poll,index|
      %tr
        %td #{poll.name}
        %td #{poll.try(:category).try(:name)}
        %td #{poll.poll_type}
        %td #{poll.try(:questions).try(:count)}
        %td N/A
        %td.text-center.editing-td
          = link_to poll_path(poll),remote: true do
            %i.fa.fa-eye{title: "Show"}
          = link_to "javascript:;",remote: true do
            %i.fa.fa-pencil{title: "Edit"}
          = link_to poll_path(poll) do
            %i.fa.fa-object-group{title: "Widgets"}
        %td.text-center.delet-td

          = link_to poll_path(poll),method: "delete", :data => {:confirm => 'Are you sure you want to delete this poll?'} do
            %i.fa.fa-trash
= will_paginate @polls,class: "poll-paginate pagination-style"
#viewPoll.modal.fade.in.text-center{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
:javascript
  $('.poll-paginate a').attr('data-remote', true);

app/views/polls/_questions_table.html.haml
%table.table.table-bordered.table-striped.question-table.polls-table
  %thead
    %tr
      %th Question
      %th Category
      %th Type
      %th Poll title
      %th
      %th.delet-td
  %tbody
    - @questions.each do |question|
      %tr
        %td #{question.question}
        %td #{question.try(:category).try(:name)}
        %td #{question.question_type}
        %td #{question.polls.first.try(:name).blank? ? "N/A" : question.polls.first.try(:name)}
        %td.text-center.editing-td
          = link_to question_path(question),remote: true do
            %i.fa.fa-eye
        %td.text-center.delet-td.add-to-poll-checkbox
          .checkbox
            %p
              %input.add-to-poll{:type => "checkbox", "data-value" => "#{question.to_json.html_safe}",value: "#{question.id}"}>
              add to poll
= will_paginate @questions,class: "poll-paginate pagination-style"
:javascript
  $('.poll-paginate a').attr('data-remote', true);

app/views/polls/_show.html.haml
.modal-dialog{:role => "document"}
  .modal-content
    .modal-body
      %h1 View Question
      %p #{@category.name}
      .w3-content.w3-display-container
        - @poll_questions.each_with_index do |question,index|
          .mySlides.show-question
            .row
              .col-sm-4
                %div.profile-image{:type => "file"}
                  %img#question-show-image{:src => question.image.present? ? question.image.thumb :  asset_path("avatar.png")}
              .col-sm-8
                .field.form-group
                  %p #{question.question}
                .field.form-group
                  - if question.question_type == "Multi"
                    %ul.question-list.edit-question
                      - question.options.each_with_index do |opt,ind|
                        %li
                          %input.form-control{:name => "question[options][#{ind+1}]",:disabled => true, :type => "text",:id=> "question_options",value: opt.second}
                  - else
                    %ul.radio-list
                      %li
                        %label.radio-inline
                          %input{:name => "question[correct_option]",:disabled => true, :type => "radio", :value => "true"}>
                          TRUE
                      %li
                        %label.radio-inline
                          %input{:name => "question[correct_option]",:disabled => true, :type => "radio", :value => "false"}>
                          FALSE
        %span.right#question-number 1/#{@poll_questions.count}
        %button.w3-display-left.question-show-left#slide-left{:onclick => "plusDivs(-1)",:type=>"button",disabled: "true"} ❮
        %button.w3-display-right.question-show-right#slide-right{:onclick => "plusDivs(1)",:type=>"button"} ❯
:javascript
  plusDivs(0)

app/views/polls/_widget.html.haml
.polling-widget-content.polling-widget-display-container
  - @poll_questions.each_with_index do |question,index|
    .polling-widget-slides.show-question
      .row
        .col-sm-4
          %div.profile-image{:type => "file"}
            %img#question-show-image{:src => question.image.present? ? question.image.thumb :  asset_path("avatar.png")}
        .col-sm-8
          .field.form-group
            %p #{question.question}
          .field.form-group
            - if question.question_type == "Multi"
              %ul.question-list.edit-question
                - question.options.each_with_index do |opt,ind|
                  %li
                    %input.form-control{:name => "question[options][#{ind+1}]",:disabled => true, :type => "text",:id=> "question_options",value: opt.second}
            - else
              %ul.radio-list
                %li
                  %label.radio-inline
                    %input{:name => "question[correct_option]",:disabled => true, :type => "radio", :value => "true"}>
                    TRUE
                %li
                  %label.radio-inline
                    %input{:name => "question[correct_option]",:disabled => true, :type => "radio", :value => "false"}>
                    FALSE
  %span.right#question-number 1/#{@poll_questions.count}
  %button.polling-widget-display-left.question-show-left#polling-widget-slide-left{:onclick => "pollingWidgetPlusDivs(-1)",:type=>"button",disabled: "true"} ❮
  %button.polling-widget-display-right.question-show-right#polling-widget-slide-right{:onclick => "pollingWidgetPlusDivs(1)",:type=>"button"} ❯
:javascript
  pollingWidgetPlusDivs(0)

app/views/polls/index.html.haml
.poll-page
  - if current_admin.super_admin?
    .margin-bottom
      = link_to "Create New Poll",new_poll_path,class: "btn btn-success"
  %h1 Browse Created polls
  .row.margin-bottom#browse-polls
    .col-md-3
      = select_tag "categories", content_tag(:option,'Category',:value=>"") + options_from_collection_for_select(@categories, "id", "name"),class: "form-control get-created-category"
    .col-md-3
      = select_tag "type", content_tag(:option,'Type',:value=>"") + "<option>Multi</option><option>T/F</option>".html_safe,class: "form-control get-created-type"
  %img{:src => asset_path("loader.gif"),class: "poll-loader hide" }
  #polls-table
    = render "polls_table"

app/views/polls/index.js.erb
$("#polls-table").html("<%= escape_javascript(render 'polls_table') %>")

app/views/polls/new.html.haml
.poll-page
  %h1 Create your poll
  = form_for @poll, class: "form-horizontal" do |f|
    .row.polls-selects
      = f.label "Poll Title/Name", class: "control-label"
      %br
      .col-sm-4
        = f.text_field :name, class: "form-control poll-name"
      .col-md-3
        = f.select :category_id,content_tag(:option,'Category',:value=>"") + options_from_collection_for_select(@categories, 'id', 'name'),{},class: 'form-control get-category'
      .col-md-3
        = f.select :poll_type,content_tag(:option,'Type',:value=>"") + "<option>Multi</option><option>T/F</option>".html_safe,{},class: 'form-control get-type'
    = f.hidden_field :admin_id,value: current_admin.id
    = hidden_field_tag "question_ids",'',id: "set-question-ids"
    %h1 Questions for polls
    %img{:src => asset_path("loader.gif"),class: "question-loader hide" }
    #questions-table.margin-bottom.hide
      = render "questions_table"
    #preview-poll.margin-bottom.hide
      %h1 Preview Poll
      %br
      .w3-content.w3-display-container
        #carousel-display
        %button.w3-button.w3-black.w3-display-left#slide-left{:onclick => "plusDivs(-1)",:type=>"button",disabled: "true"} ❮
        %button.w3-button.w3-black.w3-display-right#slide-right{:onclick => "plusDivs(1)",:type=>"button"} ❯
        %span.right#question-number.preview-count
      .actions.poll-preview-buttons
        = link_to "Cancel",polls_path,class: "btn btn-questioin"
        = f.submit "Save Poll",class: "btn btn-questioin create-poll"
#viewQuestion.modal.fade.in.text-center{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}

app/views/polls/show.html.haml
.poll-show
  %h1 #{@poll.name}
  #myCarousel-468.px468.carousel.slide{"data-ride" => "carousel"}
    / Wrapper for slides
    .carousel-inner
      - @poll_questions.each_with_index do |question,index|
        .item.show-question{class: ("active" if index == 0)}
          .row
            .col-sm-4
              %div.profile-image{:type => "file"}
                %img#question-show-image{:src => question.image.present? ? question.image.thumb :  asset_path("avatar.png")}
            .col-sm-8
              .field.form-group
                %p #{question.question}
              .field.form-group
                - if question.question_type == "Multi"
                  %ul.question-list.edit-question
                    - question.options.each_with_index do |opt,ind|
                      %li
                        %input.form-control{:name => "question[options][#{ind+1}]",:disabled => true, :type => "text",:id=> "question_options",value: opt.second}
                - else
                  %ul.radio-list
                    %li
                      %label.radio-inline
                        %input{:name => "question[correct_option]",:disabled => true, :type => "radio", :value => "true"}>
                        TRUE
                    %li
                      %label.radio-inline
                        %input{:name => "question[correct_option]",:disabled => true, :type => "radio", :value => "false"}>
                        FALSE
    / Left and right controls
    %button.w3-display-left.widget-show-left{"data-slide" => "prev", :href => "#myCarousel-468"}
      %span.fa.fa-chevron-left
      %span.sr-only Previous
    %button.w3-display-right.widget-show-right{"data-slide" => "next", :href => "#myCarousel-468"}
      %span.fa.fa-chevron-right
      %span.sr-only Next
  %button.btn.btn-wirte{"data-target" => "#myModal468", "data-toggle" => "modal", :type => "button"}
    Grab the code
  %span Size: 468*60
  #myModal468.modal.fade.in.new-category{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        .modal-body
          %h1 Grab the code
          .field.form-group
            = text_area_tag :code, "<script src='http://c17cfaa4.ngrok.io/assets/widgets.js' type='text/javascript'></script>\n<div id='widget-container' data-value='#{@poll.id}' class='px468'></div>",class: "form-control",rows: 3
          .actions.modal-btn-area
  #myCarousel-234.px234.carousel.slide{"data-ride" => "carousel"}
    / Wrapper for slides
    .carousel-inner
      - @poll_questions.each_with_index do |question,index|
        .item.show-question{class: ("active" if index == 0)}
          .row
            .col-sm-4
              %div.profile-image{:type => "file"}
                %img#question-show-image{:src => question.image.present? ? question.image.thumb :  asset_path("avatar.png")}
            .col-sm-8
              .field.form-group
                %p #{question.question}
              .field.form-group
                - if question.question_type == "Multi"
                  %ul.question-list.edit-question
                    - question.options.each_with_index do |opt,ind|
                      %li
                        %input.form-control{:name => "question[options][#{ind+1}]",:disabled => true, :type => "text",:id=> "question_options",value: opt.second}
                - else
                  %ul.radio-list
                    %li
                      %label.radio-inline
                        %input{:name => "question[correct_option]",:disabled => true, :type => "radio", :value => "true"}>
                        TRUE
                    %li
                      %label.radio-inline
                        %input{:name => "question[correct_option]",:disabled => true, :type => "radio", :value => "false"}>
                        FALSE
    / Left and right controls
    %button.w3-display-left.widget-show-left{"data-slide" => "prev", :href => "#myCarousel-234"}
      %span.fa.fa-chevron-left
      %span.sr-only Previous
    %button.w3-display-right.widget-show-right{"data-slide" => "next", :href => "#myCarousel-234"}
      %span.fa.fa-chevron-right
      %span.sr-only Next
  %button.btn.btn-wirte{"data-target" => "#myModal234", "data-toggle" => "modal", :type => "button"}
    Grab the code
  %span Size: 234*60
  #myModal234.modal.fade.in.new-category{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        .modal-body
          %h1 Grab the code
          .field.form-group
            = text_area_tag :code, "<script src='http://c17cfaa4.ngrok.io/assets/widgets.js' type='text/javascript'></script>\n<div id='widget-container' data-value='#{@poll.id}' class='px234'></div>",class: "form-control",rows: 3
          .actions.modal-btn-area
  #myCarousel-300-100.px300-100.carousel.slide{"data-ride" => "carousel"}
    / Wrapper for slides
    .carousel-inner
      - @poll_questions.each_with_index do |question,index|
        .item.show-question{class: ("active" if index == 0)}
          .row
            .col-sm-4
              %div.profile-image{:type => "file"}
                %img#question-show-image{:src => question.image.present? ? question.image.thumb :  asset_path("avatar.png")}
            .col-sm-8
              .field.form-group
                %p #{question.question}
              .field.form-group
                - if question.question_type == "Multi"
                  %ul.question-list.edit-question
                    - question.options.each_with_index do |opt,ind|
                      %li
                        %input.form-control{:name => "question[options][#{ind+1}]",:disabled => true, :type => "text",:id=> "question_options",value: opt.second}
                - else
                  %ul.radio-list
                    %li
                      %label.radio-inline
                        %input{:name => "question[correct_option]",:disabled => true, :type => "radio", :value => "true"}>
                        TRUE
                    %li
                      %label.radio-inline
                        %input{:name => "question[correct_option]",:disabled => true, :type => "radio", :value => "false"}>
                        FALSE
    / Left and right controls
    %button.w3-display-left.widget-show-left{"data-slide" => "prev", :href => "#myCarousel-300-100"}
      %span.fa.fa-chevron-left
      %span.sr-only Previous
    %button.w3-display-right.widget-show-right{"data-slide" => "next", :href => "#myCarousel-300-100"}
      %span.fa.fa-chevron-right
      %span.sr-only Next
  %button.btn.btn-wirte{"data-target" => "#myModal300-100", "data-toggle" => "modal", :type => "button"}
    Grab the code
  %span Size: 300*100
  #myModal300-100.modal.fade.in.new-category{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        .modal-body
          %h1 Grab the code
          .field.form-group
            = text_area_tag :code, "<script src='http://c17cfaa4.ngrok.io/assets/widgets.js' type='text/javascript'></script>\n<div id='widget-container' data-value='#{@poll.id}' class='px300-100'></div>",class: "form-control",rows: 3
          .actions.modal-btn-area
  #myCarousel.px300.carousel.slide{"data-ride" => "carousel"}
    .carousel-inner
      - @poll_questions.each_with_index do |question,index|
        .item.show-question{class: ("active" if index == 0)}
          .row
            .col-sm-4
              %div.profile-image{:type => "file"}
                %img#question-show-image{:src => question.image.present? ? question.image.thumb :  asset_path("avatar.png")}
            .col-sm-8
              .field.form-group
                %p #{question.question}
              .field.form-group
                - if question.question_type == "Multi"
                  %ul.question-list.edit-question
                    - question.options.each_with_index do |opt,ind|
                      %li
                        %input.form-control{:name => "question[options][#{ind+1}]",:disabled => true, :type => "text",:id=> "question_options",value: opt.second}
                - else
                  %ul.radio-list
                    %li
                      %label.radio-inline
                        %input{:name => "question[correct_option]",:disabled => true, :type => "radio", :value => "true"}>
                        TRUE
                    %li
                      %label.radio-inline
                        %input{:name => "question[correct_option]",:disabled => true, :type => "radio", :value => "false"}>
                        FALSE
    / Left and right controls
    %button.w3-display-left.widget-show-left{"data-slide" => "prev", :href => "#myCarousel"}
      %span.fa.fa-chevron-left
      %span.sr-only Previous
    %button.w3-display-right.widget-show-right{"data-slide" => "next", :href => "#myCarousel"}
      %span.fa.fa-chevron-right
      %span.sr-only Next
  %button.btn.btn-wirte{"data-target" => "#myModal300", "data-toggle" => "modal", :type => "button"}
    Grab the code
  %span Size: 300*250
  #myModal300.modal.fade.in.new-category{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        .modal-body
          %h1 Grab the code
          .field.form-group
            = text_area_tag :code, "<script src='http://c17cfaa4.ngrok.io/assets/widgets.js' type='text/javascript'></script>\n<div id='widget-container' data-value='#{@poll.id}' class='px300'></div>",class: "form-control",rows: 3
          .actions.modal-btn-area
  #myCarousel-728.px728.carousel.slide{"data-ride" => "carousel"}
    / Wrapper for slides
    .carousel-inner
      - @poll_questions.each_with_index do |question,index|
        .item.show-question{class: ("active" if index == 0)}
          .row
            .col-sm-4
              %div.profile-image{:type => "file"}
                %img#question-show-image{:src => question.image.present? ? question.image.thumb :  asset_path("avatar.png")}
            .col-sm-8
              .field.form-group
                %p #{question.question}
              .field.form-group
                - if question.question_type == "Multi"
                  %ul.question-list.edit-question
                    - question.options.each_with_index do |opt,ind|
                      %li
                        %input.form-control{:name => "question[options][#{ind+1}]",:disabled => true, :type => "text",:id=> "question_options",value: opt.second}
                - else
                  %ul.radio-list
                    %li
                      %label.radio-inline
                        %input{:name => "question[correct_option]",:disabled => true, :type => "radio", :value => "true"}>
                        TRUE
                    %li
                      %label.radio-inline
                        %input{:name => "question[correct_option]",:disabled => true, :type => "radio", :value => "false"}>
                        FALSE
    / Left and right controls
    %button.w3-display-left.widget-show-left{"data-slide" => "prev", :href => "#myCarousel-728"}
      %span.fa.fa-chevron-left
      %span.sr-only Previous
    %button.w3-display-right.widget-show-right{"data-slide" => "next", :href => "#myCarousel-728"}
      %span.fa.fa-chevron-right
      %span.sr-only Next
  %button.btn.btn-wirte{"data-target" => "#myModal728", "data-toggle" => "modal", :type => "button"}
    Grab the code
  %span Size: 300*900
  #myModal728.modal.fade.in.new-category{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        .modal-body
          %h1 Grab the code
          .field.form-group
            = text_area_tag :code, "<script src='http://c17cfaa4.ngrok.io/assets/widgets.js' type='text/javascript'></script>\n<div id='widget-container' data-value='#{@poll.id}' class='px728'></div>",class: "form-control",rows: 3
          .actions.modal-btn-area

app/views/polls/show.js.erb
$("#viewPoll").html("<%= escape_javascript(render 'show') %>")
$("#viewPoll").modal("show")

app/views/polls/update_questions.js.erb
$("#questions-table").html("<%= escape_javascript(render 'questions_table') %>")