config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: { registrations: "admin/registrations",sessions: "admin/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "admin#account"
  get '/sign_in', to: 'static_pages#index'

  resources :admin, except: [:create] do
    member do
      get :account
    end
  end

  resources :categories

  resources :questions

  resources :polls do
    collection do
      get :update_questions
      get :get_widget
    end
  end

  post 'create_admin' => 'admin#create', as: :create_admin

end

app/views/layouts/_admin_sidebar.html.haml
.col-md-2.col-sm-2.col-xs-2
  .mobile-menu
    %aside#sidebar
      %a#showLeft{:href => "javascript:;"}
        %span
        %span
        %span
      %nav#cbp-spmenu-s1.cbp-spmenu.cbp-spmenu-vertical.cbp-spmenu-left.navarea
        %ul.nav-area
          %li{ class: "#{active_class('categories','index')}" }
            = link_to "Categories", categories_path
          %li{ class: "#{active_class('questions','index')}" }
            = link_to "Questions", questions_path
          %li{ class: "#{active_class('polls','index')}" }
            = link_to "Polls", polls_path
          %li
            %a{:href => "#"} Widgets
          %li
            = link_to "My Account",account_admin_path(current_admin)
          %li{ class: "#{active_class('admin','index')}" }
            = link_to "Admins", admin_index_path

app/views/layouts/_flash_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .container-fluid
      %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
        %a.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
        = content_tag :div, msg, :id => "flash_#{name}"
.notifications.top-right

app/views/layouts/_header.html.haml
#header
  .header-holder
    .row
      .col-md-4.col-sm-4.col-xs-4.header-heading
        %h2 Logo
      .col-md-4.col-sm-4.col-xs-4.text-center
        - if current_admin.super_admin?
          %h2 Admin
        - else
          %h2 Writer
      .col-md-4.col-sm-4.col-xs-4.text-right.right-penal
        .icon-download
          = link_to destroy_admin_session_path,method: "delete", :data => {:confirm => 'Are you sure you want to log out?'} do
            %i.fa.fa-sign-out

app/views/layouts/_sidebar.html.haml
.col-md-2.col-sm-2.col-xs-2
  .mobile-menu
    %aside#sidebar
      %a#showLeft{:href => "javascript:;"}
        %span
        %span
        %span
      %nav#cbp-spmenu-s1.cbp-spmenu.cbp-spmenu-vertical.cbp-spmenu-left.navarea
        %ul.nav-area
          %li{ class: "#{active_class('questions','index')}" }
            = link_to "Questions", questions_path
          %li{ class: "#{active_class('polls','index')}" }
            = link_to "Polls", polls_path
          %li
            %a{:href => "#"} Widgets
          %li
            = link_to "My Account",account_admin_path(current_admin)

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pollingwidget
    = csrf_meta_tags
    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet", integrity: "sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN", crossorigin: "anonymous"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash_messages'
    = yield

app/views/layouts/dashboard.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pollingwidget
    = csrf_meta_tags
    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet", integrity: "sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN", crossorigin: "anonymous"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.cbp-spmenu-push
    = render 'layouts/header'
    .twocolumns
      - if current_admin.super_admin?
        = render 'layouts/admin_sidebar'
      - else
        = render 'layouts/sidebar'
      #content.content-full-width
        .admin-table
          = render 'layouts/flash_messages'
          = yield